// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-eA4RDCxrAtMDuc2GTJrEfx-h9PZXEWs',
    appId: '1:915645629444:web:cea63f5c414bc04d78e151',
    messagingSenderId: '915645629444',
    projectId: 'quest-in-air',
    authDomain: 'quest-in-air.firebaseapp.com',
    storageBucket: 'quest-in-air.appspot.com',
    measurementId: 'G-VQJ1W306XP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS-eXXvB1FS2QWY3UucS-3p-W1PjPzPIE',
    appId: '1:915645629444:android:f97395613a2e47b378e151',
    messagingSenderId: '915645629444',
    projectId: 'quest-in-air',
    storageBucket: 'quest-in-air.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3LHCZAkjV0cKBdjuqD-IBSHV3LmA1hk4',
    appId: '1:915645629444:ios:f2e10d22ed89114178e151',
    messagingSenderId: '915645629444',
    projectId: 'quest-in-air',
    storageBucket: 'quest-in-air.appspot.com',
    iosBundleId: 'com.example.questInAir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3LHCZAkjV0cKBdjuqD-IBSHV3LmA1hk4',
    appId: '1:915645629444:ios:f2e10d22ed89114178e151',
    messagingSenderId: '915645629444',
    projectId: 'quest-in-air',
    storageBucket: 'quest-in-air.appspot.com',
    iosBundleId: 'com.example.questInAir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-eA4RDCxrAtMDuc2GTJrEfx-h9PZXEWs',
    appId: '1:915645629444:web:57793bddc85ff46a78e151',
    messagingSenderId: '915645629444',
    projectId: 'quest-in-air',
    authDomain: 'quest-in-air.firebaseapp.com',
    storageBucket: 'quest-in-air.appspot.com',
    measurementId: 'G-TPPFYP6ZT6',
  );
}
